In this section i had down some data manipulation techniques using numpy and pandas

In [1]:
import pandas as pd

In [17]:
df=pd.read_csv('Online Sales Data 1.csv')

In [18]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,1/1/2024,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,1/5/2024,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,NaN,159.99,Europe,PayPal
236,10237,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [5]:
df.head(10)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card

In [20]:
df.tail(10)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
230,10231,8/18/2024,Clothing,Adidas Originals Trefoil Hoodie,4,64.99,259.96,Asia,Debit Card
231,10232,8/19/2024,Books,Dune by Frank Herbert,2,9.99,19.98,North America,Credit Card
232,10233,8/20/2024,Beauty Products,Fresh Sugar Lip Treatment,1,24.00,24.00,Europe,PayPal
233,10234,8/21/2024,Sports,Hydro Flask Standard Mouth Water Bottle,3,32.95,98.85,Asia,Credit Card
234,10235,8/22/2024,Electronics,Bose QuietComfort 35 II Wireless Headphones,1,299.00,299.00,North America,Credit Card
235,10236,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,NaN,159.99,Europe,PayPal
236,10237,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [21]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   234.000000     240.000000
mean      10120.50000    2.158333   240.683718     335.699375
std          69.42622    1.322454   433.996373     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.622500      62.965000
50%       10120.50000    2.000000    89.995000     179.970000
75%       10180.25000    3.000000   286.747500     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [22]:
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [23]:
df.head(10)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,1/1/2024,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,1/5/2024,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,1/6/2024,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,1/7/2024,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,1/8/2024,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,1/9/2024,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
9,10010,1/10/2024,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card

In [24]:
df.isnull()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
235,False,False,False,False,False,True,False,False,False
236,False,False,False,False,False,False,False,False,False
237,False,False,False,False,False,False,False,False,False
238,False,False,False,False,False,False,False,False,False
239,False,False,False,False,False,False,False,False,False

In [25]:
print(df.isnull().any(axis=1))

0      False
1      False
2      False
3      False
4      False
       ...
235     True
236    False
237    False
238    False
239    False
Length: 240, dtype: bool

In [26]:
df.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          6
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

In [27]:
df.fillna(0)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,1/1/2024,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,1/5/2024,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,0.00,159.99,Europe,PayPal
236,10237,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [29]:
df.head(20)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,1/1/2024,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,1/5/2024,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,1/6/2024,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,1/7/2024,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,1/8/2024,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,1/9/2024,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
9,10010,1/10/2024,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card
10,10011,1/11/2024,Beauty Products,Chanel No. 5 Perfume,1,129.99,129.99,Europe,PayPal
11,10012,1/12/2024,Sports,Babolat Pure Drive Tennis Racket,3,199.99,599.97,Asia,Credit Card
12,10013,1/13/2024,Electronics,Samsung Galaxy Tab S8,2,749.99,1499.98,North America,Credit Card
13,10014,1/14/2024,Home Appliances,Keurig K-Elite Coffee Maker,1,189.99,189.99,Europe,PayPal
14,10015,1/15/2024,Clothing,North Face Down Jacket,2,249.99,499.98,Asia,Debit Card
15,10016,1/16/2024,Books,"Salt, Fat, Acid, Heat by Samin Nosrat",3,35.99,107.97,North America,Credit Card
16,10017,1/17/2024,Beauty Products,Dyson Supersonic Hair Dryer,1,399.99,399.99,Europe,PayPal
17,10018,1/18/2024,Sports,Manduka PRO Yoga Mat,4,119.99,479.96,Asia,Credit Card
18,10019,1/19/2024,Electronics,Garmin Forerunner 945,2,499.99,999.98,North America,Credit Card
19,10020,1/20/2024,Home Appliances,Ninja Professional Blender,1,99.99,99.99,Europe,PayPal

In [31]:
df.isnull().sum()# it is 6 beacuse i had not saved it in a new variable okay

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          6
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

In [32]:
#filling missing value with mean of the column
df['new_unit_price']=df['Unit Price'].fillna(df['Unit Price'].mean())
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,new_unit_price
0,10001,1/1/2024,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.990000
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.990000
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.990000
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.990000
4,10005,1/5/2024,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.990000
...,...,...,...,...,...,...,...,...,...,...
235,10236,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,NaN,159.99,Europe,PayPal,240.683718
236,10237,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,90.000000
237,10238,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,10.990000
238,10239,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.000000
239,10240,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,29.990000

In [36]:
#renaming columns 
df.rename(columns={'Unit Price':'Old Price'})

,Transaction ID,Date,Product Category,Product Name,Units Sold,Old Price,Total Revenue,Region,Payment Method,new_unit_price
0,10001,1/1/2024,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.990000
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.990000
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.990000
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.990000
4,10005,1/5/2024,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.990000
...,...,...,...,...,...,...,...,...,...,...
235,10236,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,NaN,159.99,Europe,PayPal,240.683718
236,10237,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,90.000000
237,10238,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,10.990000
238,10239,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.000000
239,10240,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,29.990000

In [37]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,new_unit_price
0,10001,1/1/2024,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.990000
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.990000
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.990000
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.990000
4,10005,1/5/2024,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.990000
...,...,...,...,...,...,...,...,...,...,...
235,10236,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,NaN,159.99,Europe,PayPal,240.683718
236,10237,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,90.000000
237,10238,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,10.990000
238,10239,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.000000
239,10240,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,29.990000

In [39]:
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
new_unit_price      float64
dtype: object

In [40]:
#changing dtypes 
df['Units_Sold_new']=df['Units Sold'].astype(float)
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
new_unit_price      float64
Units_Sold_new      float64
dtype: object

In [41]:
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
new_unit_price      float64
Units_Sold_new      float64
dtype: object

In [44]:
(df)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,new_unit_price,Units_Sold_new
0,10001,1/1/2024,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.990000,2.0
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.990000,1.0
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.990000,3.0
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.990000,4.0
4,10005,1/5/2024,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.990000,1.0
...,...,...,...,...,...,...,...,...,...,...,...
235,10236,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,NaN,159.99,Europe,PayPal,240.683718,1.0
236,10237,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,90.000000,3.0
237,10238,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,10.990000,3.0
238,10239,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.000000,1.0
239,10240,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,29.990000,2.0

In [46]:
df1=df['Units_Sold_new'].apply(lambda x:x*2 )
df1

0      4.0
1      2.0
2      6.0
3      8.0
4      2.0
      ...
235    2.0
236    6.0
237    6.0
238    2.0
239    4.0
Name: Units_Sold_new, Length: 240, dtype: float64

In [48]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,new_unit_price,Units_Sold_new
0,10001,1/1/2024,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.990000,2.0
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.990000,1.0
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.990000,3.0
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.990000,4.0
4,10005,1/5/2024,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.990000,1.0
...,...,...,...,...,...,...,...,...,...,...,...
235,10236,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,NaN,159.99,Europe,PayPal,240.683718,1.0
236,10237,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,90.000000,3.0
237,10238,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,10.990000,3.0
238,10239,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.000000,1.0
239,10240,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,29.990000,2.0

In [50]:
#data aggregation and grouping 
df.groupby('Product Category')['Total Revenue'].mean()

Product Category
Beauty Products     65.54750
Books               46.54825
Clothing           203.22325
Electronics        874.56025
Home Appliances    466.15400
Sports             358.16300
Name: Total Revenue, dtype: float64

In [53]:
#based on two categories 
df.groupby(['Product Category','Region'])['Total Revenue'].sum()

Product Category  Region
Beauty Products   Europe            2621.90
Books             North America     1861.93
Clothing          Asia              8128.93
Electronics       North America    34982.41
Home Appliances   Europe           18646.16
Sports            Asia             14326.52
Name: Total Revenue, dtype: float64

In [54]:
#multiple aggregation functions
df.groupby(['Product Category','Region'])['Total Revenue'].agg(['count','sum','mean'])

                                count       sum       mean
Product Category Region
Beauty Products  Europe            40   2621.90   65.54750
Books            North America     40   1861.93   46.54825
Clothing         Asia              40   8128.93  203.22325
Electronics      North America     40  34982.41  874.56025
Home Appliances  Europe            40  18646.16  466.15400
Sports           Asia              40  14326.52  358.16300

In [62]:
#mering and joining 
data1={"key":["A","B","D"],"Value1":[1,2,3]}
data2={"key":["A","B","E"],"Value2":[1,5,4]}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
print(df1)

  key  Value1
0   A       1
1   B       2
2   D       3

In [63]:
print(df2)

  key  Value2
0   A       1
1   B       5
2   E       4

In [64]:
pd.merge(df1,df2,on='key',how="inner")

  key  Value1  Value2
0   A       1       1
1   B       2       5

In [65]:
pd.merge(df1,df2,on='key',how="outer")

  key  Value1  Value2
0   A     1.0     1.0
1   B     2.0     5.0
2   D     3.0     NaN
3   E     NaN     4.0

In [66]:
pd.merge(df1,df2,on='key',how="left")

  key  Value1  Value2
0   A       1     1.0
1   B       2     5.0
2   D       3     NaN

In [67]:
pd.merge(df1,df2,on='key',how="right")

  key  Value1  Value2
0   A     1.0       1
1   B     2.0       5
2   E     NaN       4